### ISSUE TITLE
trying to match training performance

### ISSUE THREAD

**Issue by AruniRC** [yl-1993/learn-to-cluster#11]
The reported f-score for GCN-D (0.7, 0.75) is **79.26**: https://github.com/yl-1993/learn-to-cluster#results-on-part1_test

I ran the provided training script, the f-score is **78.74**.  This is very close, but still the difference could be a bug at my end. Could you please confirm these numbers, or suggest some ways to check if anything is going wrong?

**Comment by yl-1993** [comment]
@AruniRC Hi Aruni, thanks for trying our code. Your trained performance is close to my result, as reported in PR https://github.com/yl-1993/learn-to-cluster/pull/6. These setting is a demonstration and there are some other training skills to further increase the performance, e.g., more cluster proposals, larger epochs. For better performance, you can checkout the config `dsgcn/configs/cfg_train_8_prpsl.yaml` in `dev` branch.

**Comment by AruniRC** [comment]
Thank you. I think 78.74 (my recreation) and 78.80 (your results in PR) are close enough, so probably no setup/runtime bugs at my end.
