### ISSUE TITLE
Comparison to Spectral Clustering

### ISSUE THREAD

**Issue by jlevy44** [yl-1993/learn-to-cluster#13]
Is there a comparison of these clustering methods to results obtained using spectral clustering on the affinity graph?

Thanks!

**Comment by jlevy44** [comment]
I see it in the code, but no benchmark.

**Comment by yl-1993** [comment]
@jlevy44 That's a good catch. In our benchmarks, the smallest setting contains 580K samples, thus the spectral clustering suffers from memory issue (OOM). We may provide a smaller setting in benchmarks to compare with spectral clustering.

**Comment by jlevy44** [comment]
Maybe this could help with the computation: https://ml.dask.org/modules/generated/dask_ml.cluster.SpectralClustering.html# ?
Or any method that avoids using a dense computation of the affinity? That seems to be the bottleneck.

**Comment by yl-1993** [comment]
@jlevy44 Sorry for the late reply.
I try the recommended [dask-ml](https://ml.dask.org/clustering.html) and it works well on the 580K samples.
This PR https://github.com/yl-1993/learn-to-cluster/pull/26 will include it into the baseline methods. Thanks!

**Comment by jlevy44** [comment]
Thanks!
