### ISSUE TITLE
GCN-D predicting IoU or IoP or both?

### ISSUE THREAD

**Issue by AruniRC** [yl-1993/learn-to-cluster#15]
Hi, 

in this line the GCN-D model outputs a single scalar value for each sample. Is this IoU or IoP?

```
output, loss = model(data, return_loss=True)
```

https://github.com/yl-1993/learn-to-cluster/blob/master/dsgcn/test_cluster_det.py#L40

The paper states that GCN-D is trained to predict *both* values for a given cluster proposal. Could you please explain this in the code?

thank you,
Aruni

**Comment by yl-1993** [comment]
@AruniRC Thanks for the question and sorry for the late reply. As shown in https://github.com/yl-1993/learn-to-cluster/blob/master/dsgcn/datasets/cluster_det_processor.py#L37, `output` refers to IoU here. We intend to show that GCN-D can work independently, thus we do not involve IoP in this stage.

For the full training process, we need to predict IoP to select suitable proposals for GCN-S.
