### ISSUE TITLE
Question about generating proposals

### ISSUE THREAD

**Issue by honglongcai** [yl-1993/learn-to-cluster#18]
Thanks for your wonderful work. 
I have a question in clusters proposal section. In your original paper, you proposed a cluster proposal method. I think, knn is not involved in that section. However, in your code proposals/generate_proposals.py, knn method with parameters knn_method='faiss' and k=80 is used. I am wondering, what this knn method is used for and why you choose k=80. 
Thanks for your time.

**Comment by yl-1993** [comment]
@honglongcai You're right that knn is not part of cluster proposal algorithm. In `proposals/generate_proposals.py`, it actually involves two parts, i.e., build affinity graph and generate proposals. The parameters associated with knn is involved in the first part.
Specifically, (1) `knn_method` helps us to find the k-nearest neighbors of each node and `k` determines the number of neighbors. By connecting each node with its `k` neighbors, we get the affinity graph. (2) `faiss` is one of the most efficient knn method which is capable of dealing with millions of nodes. It can also be replaced with other knn algorithm such as `hnsw`. (3) In our experiments, we found the choice of `k` is not very sensitive, as long as it is in a reasonable range (30~100).

**Comment by honglongcai** [comment]
Got it, thanks for your reply.
