### ISSUE TITLE
为什么不用更深的gcn? 

### ISSUE THREAD

**Issue by zsz00** [yl-1993/learn-to-cluster#23]
为什么不用更深的gcn? 

我看论文中只用了2层的gcn, 为什么不用更深的gcn网络, 那样是会有什么问题吗??

**Comment by yl-1993** [comment]
@zsz00 Hi, 这个在论文的Ablation Study (sec.4.3.2)的Table 3中有相关实验，如果使用的是普通gcn，本质上是对邻域不断做加权平均，在网络加深的过程中会造成over-smoothing，在我们这个问题中，和mean-pooling的效果类似，都会造成性能的下降。有其它一些相关工作使用了更深的GCN，例如[Combinational Optimization](https://arxiv.org/pdf/1810.10659.pdf)使用了20层GCN来提供NPHard的基础解, [DeepGCNs](https://arxiv.org/abs/1904.03751)在点云的语义分割上展示了可以使用更深的gcn

**Comment by zsz00** [comment]
把DeepGCNs的深层的网络 用在gcn-d中, 会有更好的效果吗?

**Comment by yl-1993** [comment]
@zsz00 目前还没有做过相关的尝试，这两个方面的进展是互补的，欢迎尝试。
