### ISSUE TITLE
关于gcn-s结构相关问题

### ISSUE THREAD

**Issue by ltm920716** [yl-1993/learn-to-cluster#25]
你好，最近自己动手复现了论文中的gcn-s部分，有一些疑问还希望解答

1. 看其他提问中，训练iou和iop可以分开单独训练，我是把最后的64-1的全连接变为64-2，分别代表iou和iop，请问这样有什么问题么，会造成一个损失主导的情况么

2. 文中对于gcn-s的label制作，随机选一个proposal中的点作为主类，其他为负类，请问论文中说的多次循环，是否指的是每个epoch对同一个proposal都进行一次主类的选择来实现的，还是说每一个epoch，对于一个proposal都要进行多次主类选择，一个样本在一个epoch中变成了多个样本

3. 在gcn-s的预测过程中，文中说的选择proposal预测出主类数量最多的一次最为最终的预测结果，请问，训练完成后，是每次inference的时候还要选一个随机种子，然后每一个数据预测多次对么？这个地方开放的代码段没有体现，个人不是很理解怎么实现的，还麻烦指点

4. iou的训练预测，源码里没有加sigmoid进行约束，但是增加gcn-s之后，iop的部分是不是在inference的时候需要加sigmoid约束更合理，那这个时候iou还需要加sigmoid约束么，反之训练iou和iop的时候是不是也应该加sigmoid，这样才能在推理的时候分布一致

5. 增加gcn-s，根据iop将对应的proposal送到gcn-s中，得到提纯的结果，请问这些新的proposal还需要重新计算gcn-d么，因为iou这个时候已经变了

感谢答疑

**Comment by yl-1993** [comment]
@ltm920716 抱歉回复迟了。问题都很细致，谢谢。

1. 这种方式也没有问题，这和multitask时从哪一层开始share的问题类似。且因为iou和iop都是0-1之间的值，所以应该不太会导致其中一个占主导，但是有可能像multitask中一样出现两个task的收敛速度不一致的问题。

2. 提到的这两种情况类似，我觉得都可以。将epoch数目增加x倍和在一个epoch中采样x次是类似的（收敛上会有一些不同）。

3. 是的，在inference的时候，对于每个样本都产生x个随机种子，然后取其中分割结果最好的一个（保留最多）。

4. 这个问题很好，iou因为用于deoverlap，只关注ranking，所以没有进行normalize，iop需要加入了normalize的处理。

5. 这也是个好问题，我们是没有重新计算gcn-d的。我们在设计的时候考虑到过这个问题，我们参考了mask-rcnn的设计，mask-rcnn在segmentation branch后，也可以再重新计算detection的bbox，但mask-rcnn没有采用这个做法。我们猜测或许是出于计算量的考虑（可能要花很多的计算资源但可能只会提升一点点效果）。但这个我们没有做过尝试，欢迎尝试。

**Comment by ltm920716** [comment]
@yl-1993 感谢细致回复，理解的更深入了
