### ISSUE TITLE
Does it support data incremental processing?

### ISSUE THREAD

**Issue by aiot-tech** [yl-1993/learn-to-cluster#30]
Thanks for sharing your outstanding work. It has been very helpful and interesting and I have a question on your code. Does it support data incremental processing?What if I want to process the data incrementally?

**Comment by yl-1993** [comment]
Hi @aiot-tech , the proposed method is not designed for incremental clustering, but I think it can be applied to incremental clustering with some adaptations.

* A naive solution is to merge the new data with the old ones and apply clustering again. It demands more computational cost but it can serve as a reference performance. (Actually, the performance of incremental clustering cannot surpass the full clustering, except there are other known priors, e.g., the new data does not share any classes with the old ones.)
* If it is known that the new data does not share any classes with the old ones, we can simply apply clustering on them separately and merge the results.
* If it is unknown whether there is overlap between new data classes and old data classes, the key lies in how to merge the new data into the old clusters. A possible solution is to decompose the problem into two stages, i.e., first apply clustering on them separately and then develop some techniques to merge clusters. For merging clusters, we can leverage the idea of super vertex to regard each cluster as a vertex for constructing an affinity graph, and then apply GCN-D and GCN-S thereon.

Besides extending the current full clustering approaches to incremental clustering, you can also design specialized algorithms  for incremental clustering.

Above are some of my thoughts but I do not test them experimentally. Let me know if you make any progress.

**Comment by aiot-tech** [comment]
Great! Thanks a lot

**Comment by Linsongrong** [comment]
@aiot-tech Hi. Have you solved this problem? Can you share your idea?
