### ISSUE TITLE
Making own custom training dataset

### ISSUE THREAD

**Issue by rose-jinyang** [yl-1993/learn-to-cluster#33]
Hello
Thanks for contributing this paper and project.
I have a question.
How should I make own custom training dataset?
Please let me know about the detailed structure of each files in training dataset.
Thanks

**Comment by yl-1993** [comment]
@rose-jinyang PR https://github.com/yl-1993/learn-to-cluster/pull/34 creates a DATASET.md to describe the detailed structure. Is the description clear for you?

**Comment by rose-jinyang** [comment]
Thanks for your update
