### ISSUE TITLE
Cluster proposal configuration for YouTube Faces

### ISSUE THREAD

**Issue by jaantoots** [yl-1993/learn-to-cluster#35]
Could you add the configuration used for the results in the paper for the YouTube Faces dataset?

I can reproduce the FastHAC baseline (ave_pre: 0.9964, ave_rec: 0.8731, fscore: 0.9307) with the provided features but unable to reproduce your results. Using the same configuration as provided for MS-Celeb-1M gives rather disappointing results, e.g. 20 prpsls config using the GCN-D model in the YTBFace download: ave_pre: 0.9442, ave_rec: 0.4964, fscore: 0.6507

Trying to increase `minsz_i0` and `maxsz_i0` to 9 and 900, respectively, yields slightly better but still inferior results: ave_pre: 0.9491, ave_rec: 0.8182, fscore: 0.8788

How did you achieve precision 96.75, recall 92.27, f1 score 94.46 in the paper (1904.02749 table 2)?

**Comment by yl-1993** [comment]
Hi @jaantoots, thanks for checking out our project. I add the related configs in commit https://github.com/yl-1993/learn-to-cluster/pull/32/commits/09c7262559079a5db68fe65b9564a39fd9a95d90 to reproduce the result on YouTube-Faces. Besides, I find the pretrained model has unexpected prefix `module.base.` and it is corrected now. You can reproduce the result by the following two steps:
1. Download the latest YouTube-Faces in [DATASET.md](https://github.com/yl-1993/learn-to-cluster/blob/master/DATASET.md) or use `python tools/download_data.py --data youtube_face`.
2. Run `scripts/dsgcn/test_cluster_det_ytb.sh`

The result is expected to be `ave_pre: 0.9674, ave_rec: 0.9225, fscore: 0.9444`, which is close to the result reported in the paper.

Feel free to have a try after PR https://github.com/yl-1993/learn-to-cluster/pull/32 is merged.

**Comment by yl-1993** [comment]
Hi @jaantoots, PR https://github.com/yl-1993/learn-to-cluster/pull/32 is merged. Feel free to have a try and let me know if there is any problem.

**Comment by jaantoots** [comment]
Many thanks for the update. This worked as expected.

As an aside, it wasn't clear from the paper that the YouTube Faces result was GCN-D only and no outlier segmentation. This is implied in multiple places in this repo so no problem but it would be great to mention this more explicitly whether GCN-S didn't improve results or you simply haven't had the time to test it. I could (re)train the models myself to see but have not got around to it either :smile:
