### ISSUE TITLE
compare with chinese_whispers

### ISSUE THREAD

**Issue by zhangming8** [yl-1993/learn-to-cluster#37]
Hi, thanks for your great work. Have you compared with chinese whispers algorithm (it's also a face clustering algorithm).

**Comment by yl-1993** [comment]
Hi @zhangming8, thanks for the suggestions. We will compare with the [Chinese Whispers](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.548.656&rep=rep1&type=pdf) clustering algorithm.

**Comment by yl-1993** [comment]
Hi @zhangming8, PR https://github.com/yl-1993/learn-to-cluster/pull/38 will add the implementation and results of Chinese Whispers clustering algorithm.

**Comment by zhangming8** [comment]
Yeah, thank you.
