### ISSUE TITLE
baseline features network

### ISSUE THREAD

**Issue by AruniRC** [yl-1993/learn-to-cluster#4]
Hi, could you please point to the codebase or network architecture used to compute the face features (i.e. the face recognition baseline model)?

thanks!

**Comment by yl-1993** [comment]
@AruniRC Hi, you can checkout [hfsoftmax](https://github.com/yl-1993/hfsoftmax) for face features extraction. We also provide some pretrained model [here](https://github.com/yl-1993/hfsoftmax/wiki).

**Comment by AruniRC** [comment]
thanks.

**Comment by jquesadap** [comment]
@yl-1993, were all the models [here](https://github.com/yl-1993/hfsoftmax/wiki) trained with the same input and feature dimentions? Thanks in advance.
