### ISSUE TITLE
Issue on testing with unlabeled data

### ISSUE THREAD

**Issue by rose-jinyang** [yl-1993/learn-to-cluster#41]
Hello
How are you?
I am going to cluster an unlabeled data with vegcn module.
How should I make a meta file?
There is not a detailed explanation for this part in DATASET.md
I set all of the labels to -1 in the meta file.

**Comment by yl-1993** [comment]
@rose-jinyang There are two ways to cluster unlabeled data.
(1) Do not pass the `label_path` in config file. (as suggested in https://github.com/yl-1993/learn-to-cluster/issues/9#issuecomment-518641561)
(2) Make the pseudo meta label as you described, but just ignore the loss and the evaluation results.

Thanks for the suggestion. We will add a detailed explanation for unlabeled data inference in DATASET.md.

**Comment by rose-jinyang** [comment]
Thanks
