### ISSUE TITLE
MS-Celeb-1M splits filenames

### ISSUE THREAD

**Issue by AruniRC** [yl-1993/learn-to-cluster#5]
Could you please share the filenames used for the train/test splits of Ms-Celeb-1M? 

The paper mentions (Sec 4.1) creating 10 random splits. To be consistent with your results, it would be very useful if you give the list of files in each split.

thank you!

**Comment by yl-1993** [comment]
@AruniRC Hi, the splits have already been shared. You can find them in https://github.com/yl-1993/learn-to-cluster/issues/2 or [README](https://github.com/yl-1993/learn-to-cluster#setup-and-get-data) (the second *[optional]*).
