### ISSUE TITLE
the relationship between model extracting features and clustering result

### ISSUE THREAD

**Issue by qiudi0127** [yl-1993/learn-to-cluster#51]
hi, here is a question about the mapping relation between model extracting features and clustering result, will the better model extracting features result in the better clustering fscore?

**Comment by yl-1993** [comment]
Hi @qiudi0127 , thanks for the question. I think it is similar to https://github.com/yl-1993/learn-to-cluster/issues/50.

Basically, it is very likely that better feature extractor would lead to better clustering results. However, as all clustering algorithms can benefit from stronger feature extractor, it is uncertain that the performance gap between our method and baseline methods will enlarge continuously. More experiments are required to show the change of performance gap.

**Comment by qiudi0127** [comment]
@yl-1993 hi, i met an issue that using the part1_test.bin and pretrained model can not get the fscore given by git.
![image](https://user-images.githubusercontent.com/26405062/86469324-bab81d00-bd6b-11ea-9e81-0899114dc039.png)

**Comment by yl-1993** [comment]
Hi @qiudi0127 , it seems that the `k` is set to 15 instead of 80 for testing?
