### ISSUE TITLE
about use vegcn for unlable feature.

### ISSUE THREAD

**Issue by Linsongrong** [yl-1993/learn-to-cluster#53]
@yl-1993 您好，我正在尝试用vegcn的方法来聚类，不过在过程中出现了问题。我是这么做的：1.先提取特征并转存.bin文件 2.在尝试vegcn，先提GCN-V特征，然后用GCN-E细分聚类。但我的feature是没有标签的，所以在运行是出错。这个.meta文件是必须的吗，我改怎么改动。期待您的回复。

**Comment by yl-1993** [comment]
@Linsongrong 您好，这个.meta文件不是必须的，可以注释掉config中的[label_path](https://github.com/yl-1993/learn-to-cluster/blob/master/vegcn/configs/cfg_train_gcnv_ms1m.py#L14)。
在[gcn_v_dataset](https://github.com/yl-1993/learn-to-cluster/blob/master/vegcn/datasets/gcn_v_dataset.py#L27)和[gcn_e_dataset](https://github.com/yl-1993/learn-to-cluster/blob/master/vegcn/datasets/gcn_e_dataset.py#L31)中都会处理label_path为None的情况。更多先前的讨论可见https://github.com/yl-1993/learn-to-cluster/issues/9

**Comment by Linsongrong** [comment]
谢谢回复，问题已解决。

**Comment by fredia** [comment]
@yl-1993 hi，我注释掉了config中的train_data的label_path，但是在训练的时候报错“AttributeError: 'GCNVDataset' object has no attribute 'labels'”，请问有什么好的解决办法嘛
