### ISSUE TITLE
train_gcn_v.py    line 45: cfg.log_level  Error

### ISSUE THREAD

**Issue by 1878708493** [yl-1993/learn-to-cluster#56]
train_gcn_v.py    
line 45: cfg.log_level     Error : Logger must be a logging.Logger object

How can I fix it ?

**Comment by yl-1993** [comment]
Hi @1878708493 , I suspect it may relate to the version of mmcv. Would you mind sharing full error message? Or you may want to try `pip install mmcv==0.2.15`?
