### ISSUE TITLE
input and feature dimentions for pretrained models

### ISSUE THREAD

**Issue by jquesadap** [yl-1993/learn-to-cluster#59]
@yl-1993  were all the models [here](https://github.com/yl-1993/hfsoftmax/wiki) trained with the same input and feature dimentions (256)? Thanks in advance.

**Comment by yl-1993** [comment]
Hi @jquesadap , these [models](https://github.com/yl-1993/hfsoftmax/wiki) are trained with the same input size (112x112) and feature dimension(256), but they are trained in a fully-supervised manner.
