### ISSUE TITLE
issue on using 'faiss-gpu'

### ISSUE THREAD

**Issue by Linsongrong** [yl-1993/learn-to-cluster#65]
@yl-1993 作者您好，我在使用faiss_gpu测试GCN-V时，效果很差。我在issues 里看到有相关的提问，您提到会尽快解决的，想问一下，您解决了吗？能提供一些在GCN-V中使用faiss_gpu的建议吗？谢谢。

**Comment by yl-1993** [comment]
@Linsongrong 您好，faiss_gpu测试效果不好的原因是train和test用了不同的knn算法，可以尝试在training的时候也用faiss_gpu来构建affinity graph。

**Comment by XHQC** [comment]
@yl-1993 @Linsongrong 你好，我也遇到同样的问题，我训练和测试都是指定了faiss_gpu,得到的效果很差，而且num_process=4会卡死，我是用一块GPU进行测试的，请问是哪里的问题呢

**Comment by hx121071** [comment]
> @yl-1993 @Linsongrong 你好，我也遇到同样的问题，我训练和测试都是指定了faiss_gpu,得到的效果很差，而且num_process=4会卡死，我是用一块GPU进行测试的，请问是哪里的问题呢
> is_precise=True 得到的dists 为全零集合，是否调用faiss_gpu 方法存在很多未处理问题呢
我也是，现在是否得到解决了呢？
