### ISSUE TITLE
Results of LCT paper

### ISSUE THREAD

**Issue by ngxbac** [yl-1993/learn-to-cluster#67]
Hi, 
Thanks for your awesome work!. 
May I ask which setting I can reproduce the results of: Learning to Cluster Faces on an Affinity Graph (CVPR2019)? 

```
GCN-D: 84.99 
GCN-D + GCN-S: 85.66 
```
Best regards,

**Comment by yl-1993** [comment]
Hi @ngxbac , we now have more effective settings, with less proposals and higher f-score. You can checkout [configs](https://github.com/yl-1993/learn-to-cluster/blob/master/dsgcn/configs/) of `dsgcn` for more details. For example, you can try [cfg_test_det_ms1m_8_prpsls](https://github.com/yl-1993/learn-to-cluster/blob/master/dsgcn/configs/cfg_test_det_ms1m_8_prpsls.py) and [cfg_test_seg_ms1m_8_prpsls](https://github.com/yl-1993/learn-to-cluster/blob/master/dsgcn/configs/cfg_test_seg_ms1m_8_prpsls.py), leading to

```
GCN-D: 86.35
GCN-D + GCN-S: 87.44
```
