### ISSUE TITLE
Slightly better Batched K-means results on YouTube Faces

### ISSUE THREAD

**Issue by AruniRC** [yl-1993/learn-to-cluster#7]
Hi, 

Firstly, thanks for the detailed codebase and results.

I was trying to replicate your results using *minibatched K-means* on *YouTubeFaces*. I took the train/test split of YTB you have linked on the website.  The test split had `140629 samples` and `1436` classes. 

Using *larger batch-size* and different num-clusters (K), we can get a better performance. Also, I get somewhat lower results when using the  *reported* settings from your [Clustering Benchmark](https://github.com/yl-1993/learn-to-cluster/wiki/Face-Clustering-Benchmarks#youtube-faces-1).

Here are the clustering results with minibatched K-means with varying batch-sizes:

| Method                     | Num clusters     | batch-size   | 	prec    | rec        | f-score    |
|:--------:                     |:--------:               |:-------:          | :---------:| :---------: | :---------:|
|       *recreation*        | K=1500              | 100             | 50.51    | 53.11      | **51.77**      |
|                                  | K=1500              | *2000*        | 80.04    | 53.17      | **63.90**      |
|   *reported* (yours)   | K=1500              | *100*          | 76.87    | 51.86      | **61.93**      |

**Comment by yl-1993** [comment]
@AruniRC Thanks a lot for reporting the results! I will double check the results in the benchmark.
