### ISSUE TITLE
Knns

### ISSUE THREAD

**Issue by redionxhepa** [yl-1993/learn-to-cluster#70]
In the dataset preparation readme file it is stated that "knns is not necessary as it can be built with the provided functions." Please can you guide me which are the relevant files/functions ? Thanks in advance!

**Comment by yl-1993** [comment]
Hi @redionxhepa , knns can be computed with functions in [utils/knn.py](https://github.com/yl-1993/learn-to-cluster/blob/master/utils/knn.py#L405).

**Comment by redionxhepa** [comment]
Thank you ! When I asked this question I had not properly looked at the code :D Anyways thank you and  congrats for the really well documented implementation.

**Comment by redionxhepa** [comment]
Hi ! I tried to run the  utils/knn.py file but I get the following error. 

Traceback (most recent call last):
  File "knn.py", line 10, in <module>
    from utils import load_data, dump_data, mkdir_if_no_exists, Timer
ModuleNotFoundError: No module named 'utils'

**Comment by redionxhepa** [comment]
The problem lies in     " from utils import (load_data, dump_data, mkdir_if_no_exists, Tim "
It should be from misc import (load_data, dump_data, mkdir_if_no_exists, Tim. In the same manner I had to change the same problems in different files of the utils folder. How were people able to run this code ? Or is it a problem with the Python version ?

**Comment by yl-1993** [comment]
@redionxhepa Hi, thanks for trying. It seems that the `utils` is not found as a package. A simple solution is to specify the `PYTHONPATH`.

```
PYTHONPATH=. python utils/knns.py
```
