### ISSUE TITLE
您好，我下载您的提取256维特征的识别模型解压包解压有问题，请问可以存在百度云盘吗

### ISSUE THREAD

**Issue by yjhuasheng** [yl-1993/learn-to-cluster#71]

**Comment by houguanqun** [comment]
请问您解压出来了吗，我也遇到了同样的问题。 @yjhuasheng

**Comment by yjhuasheng** [comment]
> 请问您解压出来了吗，我也遇到了同样的问题。 @yjhuasheng

不用解压，路径对就可以用，

**Comment by yjhuasheng** [comment]
> > 请问您解压出来了吗，我也遇到了同样的问题。 @yjhuasheng
> 
> 不用解压，他保存的model就是这个格式的，可以用的
