### ISSUE TITLE
大佬您好，我有几个问题想请教一下

### ISSUE THREAD

**Issue by yjhuasheng** [yl-1993/learn-to-cluster#72]
（1）在使用vegcn训练自己的数据时，knn中的k值是根据数据集每类的图像数设置的吗，还是说稍微大一点效果比较好？
（2）我在测试时默认设置use_gcn_feat=true，如果设置为false是不是默认测试的就是vgcn的效果，还是说这块是论文中说的对候选的置信度较高的集合在进一步的处理？

**Comment by Youskrpig** [comment]
> （1）在使用vegcn训练自己的数据时，knn中的k值是根据数据集每类的图像数设置的吗，还是说稍微大一点效果比较好？
> （2）我在测试时默认设置use_gcn_feat=true，如果设置为false是不是默认测试的就是vgcn的效果，还是说这块是论文中说的对候选的置信度较高的集合在进一步的处理？

请教下大佬，faiss_80.npz 是怎么生成的？我想生成一个2048维的 knn.npz

**Comment by yjhuasheng** [comment]
我在训练vegcn的时候这个faiss_80.npz是自动生成的

**Comment by Youskrpig** [comment]
> 我在训练vegcn的时候这个faiss_80.npz是自动生成的

奥奥 不好意思 没仔细看 # if `knn_graph_path` is not passed, it will build knn_graph automatically
谢谢了！
