### ISSUE TITLE
find an unsupervised method can get equivalent results

### ISSUE THREAD

**Issue by xiaoxiong74** [yl-1993/learn-to-cluster#74]
test result on part1_test
![image](https://user-images.githubusercontent.com/30488265/100172031-68d28800-2f02-11eb-9146-85fc983abe47.png)
[moret test resluts ](https://blog.csdn.net/qq_42189083/article/details/110002878)

**Comment by 939889912** [comment]
Can you say in more detail, such as which algorithm is used.
