### ISSUE TITLE
Pretrained Face Recognition Model in MS1M datasets

### ISSUE THREAD

**Issue by houguanqun** [yl-1993/learn-to-cluster#75]
When I decompressed the file ’resnet50_part0_train.pth.tar‘, it was found to be damaged, can you upload it again?

**Comment by yl-1993** [comment]
Hi @houguanqun , the filename maybe a little confusing as it is not a tar, but a model itself. Would you mind trying the following code?
```
import torch
ckpt = torch.load('resnet50_part0_train.pth.tar')
print(ckpt['state_dict'].keys())
```

**Comment by houguanqun** [comment]
Thank you very much!
