### ISSUE TITLE
Figure 3 in Learning to Cluster Faces via Confidence and Connectivity Estimation

### ISSUE THREAD

**Issue by longbowzhang** [yl-1993/learn-to-cluster#76]
Hi @yl-1993 Nice work!
But I have one question regarding the Fig. 3 of the paper Learning to Cluster Faces via Confidence and Connectivity Estimation.
![image](https://user-images.githubusercontent.com/7151215/101347917-be754000-38c5-11eb-9de3-dc595e32419a.png)
I am wondering why there are **three** red dots in "_ours_". If I understand correctly, one is GCN-V, and the other is GCN-V + GCN-E. Then what's the 3rd one?

**Comment by yl-1993** [comment]
Hi @longbowzhang , really sorry for the outdated reply!

From left to right, the three red dots are GCN-V, GCN-V+GCN-E(with small ρ), GCN-V + GCN-E(ρ=10%), where ρ is the portion of vertices using GCN-E as defined in Sec.3.3 .

To be more specific, the time(x-axis) for three red dots is `270s`, `413s` and `687s`, and the pairwise f-score is `87.14`, `87.23` and `87.55` respectively. The first and the last value are reported in last two rows of Table.1. For the middle value, we give a more detailed ablation study of ρ in Figure.5.
