### ISSUE TITLE
您好，想请教一下训练GCN-D时报错run out of  input

### ISSUE THREAD

**Issue by soraniiru** [yl-1993/learn-to-cluster#81]
![image](https://user-images.githubusercontent.com/78725240/107195519-67f2c200-6a2c-11eb-80cf-c6a9741519ff.png)
在训练时总会在这个2100处中止，报错run out of  input，非常疑惑，希望大佬赐教！

**Comment by yl-1993** [comment]
[run out of input](https://stackoverflow.com/questions/24791987/why-do-i-get-pickle-eoferror-ran-out-of-input-reading-an-empty-file)通常由于文件为空引起，可以检查一遍数据，或者加入try..except跳过无效数据
