### ISSUE TITLE
Clustering 512D features using pretrained model

### ISSUE THREAD

**Issue by windspirit95** [yl-1993/learn-to-cluster#83]
Hi.
I have seen that in your code the default value for feature dimension is 256, also in hfsoftmax pre-trained feature extraction model.
So I am wondering if it is possible to use your pretrained model on my extracted features, which have the dimension is 512?
Besides, is that right that to use GCN-D + GCN-S for clustering, I could test the cluster detection, then test cluster segmentation follow the instruction in https://github.com/yl-1993/learn-to-cluster/tree/master/dsgcn?
Thank you for your concern!

**Comment by Jar7** [comment]
> t to use G

Hi @windspirit95  
have you find the answer?

**Comment by windspirit95** [comment]
Since I am working on another project now, so this issue might be suspended for a while until I have time to look at it by myself again. I will let you know when I found solution for it ^^

**Comment by yl-1993** [comment]
@Jar7 @windspirit95 Hello guys, thanks for the discussion! Sorry for the late response, as I have shifted to another field.
I think using 512 or other dimension as feature is totally fine. Note that it is a supervised clustering method, so if the feature extractor changes, the clustering model should also be retrained or finetuned to achieve better results.
