### ISSUE TITLE
why using output of relu for rebuilding knn graph 

### ISSUE THREAD

**Issue by chenchaoxu** [yl-1993/learn-to-cluster#85]
I have a question about rebuilding knn graph in gcn-v inference. 
Why using the output of relu layer, not that of linear layer to get feat for rebuilding knn graph, since there are lots of zeros after passing feat map through the relu layer.

**Comment by yl-1993** [comment]
I think [ArcFace](https://arxiv.org/abs/1801.07698) reports some experiments about how to choose the output of feature extractor as face features.
