### ISSUE TITLE
is not a checkpoint filemodels/pretrained_gcn_e_ms1m.pth

### ISSUE THREAD

**Issue by changgongcheng** [yl-1993/learn-to-cluster#86]
anyone can help me？

**Comment by changgongcheng** [comment]
>>> import mmcv
>>> mmcv.__version__
'0.3.2'
>>> import faiss
>>> faiss.__version__
'1.7.0'
>>> import torch
>>> torch.__version__
'1.1.0'
>>>

**Comment by yl-1993** [comment]
Have you downloaded the pretrained models?
