### ISSUE TITLE
about extracting features

### ISSUE THREAD

**Issue by jumptoliujj** [yl-1993/learn-to-cluster#87]
I check out your code(https://github.com/yl-1993/hfsoftmax.git) and switch to branch ltc for extracting feature using pretrained model(https://drive.google.com/file/d/1eKsh7x-RUIHhIJ1R9AlUjsJdsdbh2qim/view) you provide in learn-to-cluster(https://github.com/yl-1993/learn-to-cluster/blob/master/DATASET.md). But I can not extract good features(diff from part0_train.bin you provide) and then the knn generated by my extracting features is not good as well.What's wrong with this situation？

Thanks.

**Comment by dubdynasty** [comment]
Hi, I have the same question as you. The features extracted by the pretrained model are much worse than those provided. Besides, I found that the provided features (such as part0_train.bin) are normalized, so I think the author may not use this script (https://github.com/yl-1993/hfsoftmax.git) to extract the features. Do you have any solutions?
@jumptoliujj @yl-1993

**Comment by jumptoliujj** [comment]
I have no idea. Please tell me the solution if you find out. Thanks.
@dubdynasty

**Comment by dubdynasty** [comment]
No idea, too... Perhaps we have to train the feature extractor on part0 by ourselves.
