### ISSUE TITLE
Can we manually set the number of clusters during the test

### ISSUE THREAD

**Issue by xad1997** [yl-1993/learn-to-cluster#89]
If we can, where do we need to set the parameters

**Comment by yl-1993** [comment]
Not similar to K-Means, we cannot manually set the exact number of clusters.
If you want to control the number of clusters, you may try set [`min_sz` or `max_sz`](https://github.com/yl-1993/learn-to-cluster/blob/master/dsgcn/configs/cfg_test_det_ms1m_2_prpsls.py#L40).
