### ISSUE TITLE
大佬，请教下train_cluster_seg_iop_vox.sh 的test阶段报错的问题

### ISSUE THREAD

**Issue by 1017549629** [yl-1993/learn-to-cluster#90]
运行到文件 File "./learn-to-cluster/dsgcn/test_cluster_seg.py", line 46, in test_cluster_seg
    **for proposal_folder in meta['proposal_folders']:**
报错为TypeError: 'functools.partial' object is not iterable，
请问是什么原因呢

**Comment by slacklife** [comment]
同问，你解决了吗

**Comment by yl-1993** [comment]
您好，能提供更详细一些的信息么？或者能复现错误的脚本？
