### ISSUE TITLE
About pretrained_model to get the the extracted feature 

### ISSUE THREAD

**Issue by exitxingling** [yl-1993/learn-to-cluster#94]
Hi, I have some new images generated by GAN based on the original MS1M dataset, I need to eatract the feature of the new images, 
I tried the hfsoftmax code and the  pretrained model: resnet50_part0_train.pth.tar to extract the feature of the part1_test images.
but I found that the feature is not as same as the extracted feature:part1_test.bin
How can i get the same feature as same as the extraceted feature ?

**Comment by fengzlj** [comment]
hello，你是直接在part1_test.list上做的特征提取，然后生成的feature和代码中给出的part1_test.bin不一样吗？

**Comment by yl-1993** [comment]
Hi, any message pop up when loading the pretrained model?
