### ISSUE TITLE
GCN-D MMdistributedDataparallel train

### ISSUE THREAD

**Issue by joelulu** [yl-1993/learn-to-cluster#95]
你好，我想用MMdistributedDataparallel训练GCN-D
更改了--distributed 为True
报错：
Default process group has not been initialized, please make sure to call init_process_group

**Comment by ThomaswellY** [comment]
the same question, the codes seems not supportable for distributed gpus

**Comment by yl-1993** [comment]
Yes. It currently does not support distributed training. We welcome any related PR!
