### ISSUE TITLE
关于性能

### ISSUE THREAD

**Issue by fengzlj** [yl-1993/learn-to-cluster#96]
你好，想问一下实验的性能是否存在比较大的抖动，比如LGCN在MS1M上，你给出的结果是
             precision  recall  fp 
lgcn      74.38        83.51  78.68
             74.08        83.95  78.71
             71.05        81.73  76.02
我跑出来两次结果抖动了2-3%

**Comment by yl-1993** [comment]
你好，LGCN是对原paper的复现，可以试试作者提供的代码库[gcn_clustering](https://github.com/Zhongdao/gcn_clustering)。

如果原代码库没有这个问题，那说明是此代码库复现的问题；如果原代码库也有此问题，可能需要咨询一下原作者。
