### ISSUE TITLE
How to apply lgcn for clustering on custom embeddings of collected face images?

### ISSUE THREAD

**Issue by Nigar21** [yl-1993/learn-to-cluster#97]
We have collected images and extracted their 512 embeddings via ArcFace. .npy files are ready for training & testing. How to cluster them using lgcn?

**Comment by yl-1993** [comment]
If using lgcn, you may follow the training and testing [guideline](https://github.com/yl-1993/learn-to-cluster/tree/master/lgcn) or refer to the [original repo](https://github.com/Zhongdao/gcn_clustering).
